FROM python:3.8-alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache bash build-base tesseract-ocr libmagic
RUN apk add --no-cache jpeg-dev zlib-dev
RUN apk add --no-cache tesseract-ocr-dev leptonica-dev
RUN apk add --no-cache musl-dev linux-headers gcc g++ gfortran libc-dev libffi-dev
RUN pip install -U pip
ADD requirements.txt /opt/image2pdf/requirements.txt
WORKDIR /opt/image2pdf
RUN pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
ADD src /opt/image2pdf
ADD model2/chi_sim.traineddata /usr/share/tessdata/chi_sim.traineddata
ENV TEMPDIR=/tmp/ TESSERACT_CMD=tesseract

EXPOSE 5000
CMD ["gunicorn","-c","gunicorn.py","app:app"]