FROM paddlepaddle/paddle:2.3.1-gpu-cuda11.2-cudnn8

RUN git clone -b release/2.5 https://github.com/PaddlePaddle/PaddleOCR.git /PaddleOCR &&\
    cd /PaddleOCR && pip3.7 install -r requirements.txt &&\
    pip3.7 install paddle-serving-server-gpu paddle-serving-client paddle-serving-app

WORKDIR /PaddleOCR/deploy/pdserving/

RUN wget https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar -O ch_PP-OCRv4_det_infer.tar && tar -xf ch_PP-OCRv4_det_infer.tar
RUN wget https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_rec_infer.tar -O ch_PP-OCRv4_rec_infer.tar && tar -xf ch_PP-OCRv4_rec_infer.tar
RUN python3 -m paddle_serving_client.convert --dirname ./ch_PP-OCRv4_det_infer/ \
                                             --model_filename inference.pdmodel          \
                                             --params_filename inference.pdiparams       \
                                             --serving_server ./ppocr_det_v4_serving/ \
                                             --serving_client ./ppocr_det_v4_client/
RUN python3 -m paddle_serving_client.convert --dirname ./ch_PP-OCRv4_rec_infer/ \
                                             --model_filename inference.pdmodel          \
                                             --params_filename inference.pdiparams       \
                                             --serving_server ./ppocr_rec_v4_serving/  \
                                             --serving_client ./ppocr_rec_v4_client/
ADD config.yml config.yml
ADD web_service.py web_service.py
ADD check_services.sh check_services.sh
EXPOSE 18091

CMD ["python3", "web_service.py"]