FROM paddlepaddle/paddle:3.2.2-gpu-cuda12.6-cudnn9.5

RUN git clone -b release/3.2 https://github.com/PaddlePaddle/PaddleOCR.git /PaddleOCR &&\
    cd /PaddleOCR && pip3 install -r requirements.txt paddle-serving-server-gpu paddle-serving-client paddle-serving-app

WORKDIR /PaddleOCR/deploy/pdserving/

RUN wget https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0.0/PP-OCRv5_server_det_infer.tar -O ch_PP-OCRv5_det_infer.tar && tar -xf ch_PP-OCRv5_det_infer.tar
RUN wget https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0.0//PP-OCRv5_server_rec_infer.tar -O ch_PP-OCRv5_rec_infer.tar && tar -xf ch_PP-OCRv5_rec_infer.tar

RUN python3 -m paddle_serving_client.convert --dirname ./ch_PP-OCRv5_det_infer/ \
                                             --model_filename inference.pdmodel          \
                                             --params_filename inference.pdiparams       \
                                             --serving_server ./ppocr_det_v5_serving/ \
                                             --serving_client ./ppocr_det_v5_client/
RUN python3 -m paddle_serving_client.convert --dirname ./ch_PP-OCRv5_rec_infer/ \
                                             --model_filename inference.pdmodel          \
                                             --params_filename inference.pdiparams       \
                                             --serving_server ./ppocr_rec_v5_serving/  \
                                             --serving_client ./ppocr_rec_v5_client/
ADD config.yml config.yml
ADD web_service.py web_service.py
ADD check_services.sh check_services.sh
EXPOSE 18091

CMD ["python3", "web_service.py"]