# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16pipeline_service.proto\x12%baidu.paddle_serving.pipeline_serving\"\x93\x02\n\x06Tensor\x12\x12\n\nint64_data\x18\x01 \x03(\x03\x12\x12\n\nfloat_data\x18\x02 \x03(\x02\x12\x10\n\x08int_data\x18\x03 \x03(\x05\x12\x14\n\x0c\x66loat64_data\x18\x04 \x03(\x01\x12\x13\n\x0buint32_data\x18\x05 \x03(\r\x12\x11\n\tbool_data\x18\x06 \x03(\x08\x12\x16\n\x0e\x63omplex64_data\x18\x07 \x03(\x02\x12\x17\n\x0f\x63omplex128_data\x18\x08 \x03(\x01\x12\x10\n\x08str_data\x18\t \x03(\t\x12\x11\n\tbyte_data\x18\n \x01(\x0c\x12\x11\n\telem_type\x18\x14 \x01(\x05\x12\r\n\x05shape\x18\x15 \x03(\x05\x12\x0b\n\x03lod\x18\x16 \x03(\x05\x12\x0c\n\x04name\x18\x17 \x01(\t\"\xa4\x01\n\x07Request\x12\x0b\n\x03key\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x03(\t\x12>\n\x07tensors\x18\x03 \x03(\x0b\x32-.baidu.paddle_serving.pipeline_serving.Tensor\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0e\n\x06method\x18\x05 \x01(\t\x12\r\n\x05logid\x18\x06 \x01(\x03\x12\x10\n\x08\x63lientip\x18\x07 \x01(\t\"\x87\x01\n\x08Response\x12\x0e\n\x06\x65rr_no\x18\x01 \x01(\x05\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x03(\t\x12\r\n\x05value\x18\x04 \x03(\t\x12>\n\x07tensors\x18\x05 \x03(\x0b\x32-.baidu.paddle_serving.pipeline_serving.Tensor2\x81\x01\n\x0fPipelineService\x12n\n\tinference\x12..baidu.paddle_serving.pipeline_serving.Request\x1a/.baidu.paddle_serving.pipeline_serving.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TENSOR._serialized_start=66
  _TENSOR._serialized_end=341
  _REQUEST._serialized_start=344
  _REQUEST._serialized_end=508
  _RESPONSE._serialized_start=511
  _RESPONSE._serialized_end=646
  _PIPELINESERVICE._serialized_start=649
  _PIPELINESERVICE._serialized_end=778
# @@protoc_insertion_point(module_scope)
